# Generated by Django 3.2.7 on 2021-09-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gravidade',
            fields=[
                ('id', models.AutoField(db_column='tblGravidadeID', primary_key=True, serialize=False)),
                ('categoria1', models.CharField(blank=True, db_column='Categoria1', max_length=255, null=True)),
                ('categoria2', models.CharField(blank=True, db_column='Categoria2', max_length=255, null=True)),
                ('valor', models.CharField(blank=True, db_column='Valor', max_length=255, null=True)),
                ('gravidade', models.CharField(blank=True, db_column='Gravidade', max_length=255, null=True)),
                ('acao', models.CharField(blank=True, db_column='Acao', max_length=1024, null=True)),
                ('orientacao', models.CharField(blank=True, db_column='Orientacao', max_length=255, null=True)),
                ('ativo', models.BooleanField(db_column='Ativo')),
                ('acaocorretiva', models.CharField(blank=True, db_column='AcaoCorretiva', max_length=1024, null=True)),
            ],
            options={
                'db_table': '[tblGravidade]',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdemPesquisa',
            fields=[
                ('tblsaoid', models.IntegerField(db_column='tblSAOID')),
                ('uep', models.CharField(blank=True, choices=[('PMLZ', 'PMLZ'), ('PMXL', 'PMXL'), ('P66', 'P66'), ('P67', 'P67'), ('P68', 'P68'), ('P69', 'P69'), ('P70', 'P70')], db_column='UEP', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Aguardando analista', 'Aguardando analista'), ('Ordem analisada', 'Ordem analisada')], db_column='Status', max_length=50, null=True)),
                ('ordem', models.CharField(db_column='Ordem', max_length=255, primary_key=True, serialize=False)),
                ('descricaoordem', models.CharField(blank=True, db_column='DescricaoOrdem', max_length=255, null=True)),
                ('observacaoanalista', models.TextField(blank=True, db_column='ObservacaoAnalista', null=True)),
                ('observacaoop', models.TextField(blank=True, db_column='ObservacaoOp', null=True)),
                ('resultado', models.CharField(blank=True, choices=[('Em análise', 'Em análise'), ('Conforme', 'Conforme'), ('Leve', 'Leve'), ('Média', 'Média'), ('Grave', 'Grave')], db_column='Resultado', max_length=255, null=True)),
                ('dataanalise', models.DateField(blank=True, db_column='DataAnalise', null=True)),
                ('modificacaoordem', models.DateField(blank=True, db_column='ModificacaoOrdem', null=True)),
                ('datafimreal', models.DateField(blank=True, db_column='DataFimReal', null=True)),
                ('modificadaaposanalise', models.BooleanField(db_column='ModificadaAposAnalise')),
            ],
            options={
                'db_table': '[OrdemPesquisa]',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SAO',
            fields=[
                ('tblsaoid', models.AutoField(db_column='tblSAOID', primary_key=True, serialize=False)),
                ('dataanalise', models.DateTimeField(blank=True, db_column='DataAnalise', null=True)),
                ('analisadopor', models.CharField(blank=True, db_column='AnalisadoPor', max_length=255, null=True)),
                ('ordem', models.CharField(db_column='Ordem', max_length=255)),
                ('uep', models.CharField(blank=True, db_column='UEP', max_length=255, null=True)),
                ('descricaoordem', models.CharField(blank=True, db_column='DescricaoOrdem', max_length=255, null=True)),
                ('datafimreal', models.DateTimeField(blank=True, db_column='DataFimReal', null=True)),
                ('item', models.CharField(blank=True, db_column='Item', max_length=255, null=True)),
                ('nota', models.CharField(blank=True, db_column='Nota', max_length=255, null=True)),
                ('executadopor', models.TextField(blank=True, db_column='ExecutadoPor', null=True)),
                ('confirmadopor', models.TextField(blank=True, db_column='ConfirmadoPor', null=True)),
                ('encerradotecnicamentepor', models.TextField(blank=True, db_column='EncerradoTecnicamentePor', null=True)),
                ('resultado', models.CharField(blank=True, db_column='Resultado', max_length=255, null=True)),
                ('observacaoanalista', models.TextField(blank=True, db_column='ObservacaoAnalista', null=True)),
                ('observacaolocal', models.TextField(blank=True, db_column='ObservacaoLocal', null=True)),
                ('equipamento', models.CharField(blank=True, db_column='Equipamento', max_length=255, null=True)),
                ('databaseinicio', models.DateTimeField(blank=True, db_column='DataBaseInicio', null=True)),
                ('necessitaalteracaoplano', models.CharField(blank=True, db_column='NecessitaAlteracaoPlano', max_length=255, null=True)),
                ('datacorrecaoefetuada', models.TextField(blank=True, db_column='DataCorrecaoEfetuada', null=True)),
                ('possuiaindaalgumapendencia', models.CharField(blank=True, db_column='PossuiAindaAlgumaPendencia', max_length=255, null=True)),
                ('verificacaoencerramento', models.CharField(blank=True, db_column='VerificacaoEncerramento', max_length=255, null=True)),
                ('dadospreventivosanp', models.BooleanField(blank=True, db_column='DadosPreventivosANP', null=True)),
                ('local', models.CharField(blank=True, db_column='Local', max_length=255, null=True)),
                ('if_field', models.CharField(blank=True, db_column='IF', max_length=1, null=True)),
                ('tipoordem', models.CharField(blank=True, db_column='TipoOrdem', max_length=10, null=True)),
                ('datareferencia', models.DateTimeField(blank=True, db_column='DataReferencia', null=True)),
                ('observacaoop', models.TextField(blank=True, db_column='ObservacaoOp', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': '[tblSAO]',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SAOResultado',
            fields=[
                ('id', models.AutoField(db_column='tblGravidadeID', primary_key=True, serialize=False)),
                ('categoria', models.CharField(db_column='Categoria1', max_length=255, null=True)),
                ('item', models.CharField(db_column='Valor', max_length=255, null=True)),
                ('orientacao', models.CharField(db_column='Orientacao', max_length=255, null=True)),
                ('item_sel', models.CharField(db_column='Sel', max_length=1)),
            ],
        ),
    ]
